version: '3.8'
services:
  dev-db:
    image: postgres:16
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sushil0722
      - POSTGRES_DB=nestjs
    networks:
      - sushil-network
  test-db:
    image: postgres:16
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sushil0722
      - POSTGRES_DB=nestjs
    networks:
      - sushil-network
networks:
  sushil-network:
